### ISSUE TITLE
Migration file created in the vendor folder

### ISSUE THREAD

**Issue by ankahla** [BitBagCommerce/SyliusMolliePlugin#101]
Hi, Thanks for this awsome plugin!
I am using this plugin in my sylius projet and I noticed that when generating doctrine migrations with this command `console doctrine:migrations:diff` the migration file is generated under `BitBag/SyliusMolliePlugin/Migrations/` folder instead of `src/App/Migrations/`.

Is this a known issue ? is there something that I am doing wrong ?

this is my config `config/doctrine_migrations.yaml`
```
doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        'App\Migrations': "%kernel.project_dir%/src/Migrations"
```
