### ISSUE TITLE
Error loading of CreditMemoRepository on user orders page

### ISSUE THREAD

**Issue by EggieCode** [BitBagCommerce/SyliusMolliePlugin#156]
When opening a order on the profile page on a user account. It crashes with the error that the order field does not exists.

```
Doctrine\ORM\ ORMException

Entity 'Sylius\RefundPlugin\Entity\CreditMemo' has no field 'order'. You can therefore not call 'findByOrder' on the entities' repository
```

After some research to solve this. I found that the plugin created a separate EntityManager for CreditMemo on `src/Resources/config/services/repository/credit_memo.xml`.
But I creates empty ClassMetadata, because of that the MetadataClass has no fields filled and cannot find the order field in the metadata.

I have fixed currently with this configuration:
```
sylius_resource:
    resources:
        sylius_refund.credit_memo:
            classes:
                model: Sylius\RefundPlugin\Entity\CreditMemo
                repository: BitBag\SyliusMolliePlugin\Repository\CreditMemoRepository

services:
    bitbag_sylius_mollie_plugin.repository.credit_memo_repository:
        class: BitBag\SyliusMolliePlugin\Repository\CreditMemoRepository
        factory: 
          - '@doctrine.orm.entity_manager'
          - getRepository
        arguments:
          - 'Sylius\RefundPlugin\Entity\CreditMemo:class'
```
